[package]
name = "hnsw_rs"
version = "0.1.6"
authors = ["jeanpierre.both@gmail.com"]
description = "Ann based on Hierarchical Navigable Small World Graphs from Yu.A. Malkov and D.A Yashunin"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["algorithms", "ann", "hnsw"]
repository = "https://github.com/jean-pierreBoth/hnswlib-rs"
documentation = "https://docs.rs"
edition= "2018"

[features]

# declare a feature with no dependancy to get some modulated debug print
# to be run with cargo build --features verbose_1
#verbose_1 = [ ]

[profile.release]
lto = true
opt-level = 3

[lib]
# cargo rustc --lib -- --crate-type dylib [or staticlib] or rlib (default)
# if we want to avoid specifying in advance crate-type 
lib = "hnswlib"
path = "src/lib.rs"
#crate-type = ["cdylib"]


[[examples]]
name = "random"
path = "examples/random.rs"

[[examples]]
name = "ann-glove"
path = "examples/ann-glove25-angular.rs"



[[examples]]
name = "ann-mnist"
path = "examples/ann-mnist-784-euclidean.rs"


[[examples]]
name = "levenshtein"
path = "examples/levensthein.rs"

#[[example]]

[dependencies]
# default is version spec is ^ meaning can update up to max non null version number
# cargo doc --no-deps avoid dependencies doc generation
#

serde= {version = "1.0", doc = false}
serde_derive={ version = "1.0", doc = false}


# for //
parking_lot = "0.11"
rayon = {version = "0.9.0",  doc = false}
num_cpus = {version = "1.8.0", doc = false}
simdeez = {version = "0.6", doc = false}

cpu-time = {version = "1.0", doc = false}
time = {version = "0.2",  doc = false}

ndarray = {version = "0.13", doc = false}

clap = {version = "2.29", doc = false}
#  for hashing . hashbrown still needed beccause of get_key_value(&key)
hashbrown = {version = "0.9", doc = false}
skiplist= {version = "0.3", doc=false}

rand = {version = "0.7", doc = false}
lazy_static = { version = "1.4", doc = false}
typename = {version = "0.1", doc = false}
# for benchmark reading
hdf5 = {version="0.7", doc = false}
# decreasing order of log for debug build : (max_level_)trace debug info warn error off
# decreasing order of log for release build (release_max_level_)  .. idem
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
env_logger = { version = "0.7"}
